# Generated by Django 5.1.4 on 2024-12-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Searchs',
        ),
    ]
